name: Gemini CLI

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
jobs:
  setup_gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
